version: '3.8'

services:
    backend:
        build:
            context: ./back-end
        ports:
            - "8080:8080"
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DB=everything_is_ok
        depends_on:
            - mysql
        networks:
            - my-network

    frontend:
        build:
            context: ./front-end
        ports:
            - "3000:3000"
        networks:
            - my-network

    mysql:
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: everything_is_ok
        ports:
            - "3307:3306"
        volumes:
            - mysql-data:/var/lib/mysql
            - ./mysql-init/database.sql:/docker-entrypoint-initdb.d/1.sql
        networks:
            - my-network

networks:
    my-network:
        driver: bridge

volumes:
    mysql-data: